var fuckOff = [
    '/back/:name/TARS',
    '/ballmer/:name/the AKC/TARS',
    '/bday/:name/TARS',
    '/blackadder/:name/TARS',
    '/bm/:name/TARS',
    '/bus/:name/TARS',
    '/chainsaw/:name/TARS',
    '/cocksplat/:name/TARS',
    '/dalton/:name/TARS',
    '/deraadt/:name/TARS',
    '/donut/:name/TARS',
    '/equity/:name/TARS',
    '/gfy/:name/TARS',
    '/ing/:name/TARS',
    '/keep/:name/TARS',
    '/king/:name/TARS',
    '/linus/:name/TARS',
    '/look/:name/TARS',
    '/madison/:name/TARS',
    '/nugget/:name/TARS',
    '/off/:name/TARS',
    '/outside/:name/TARS',
    '/problem/:name/TARS',
    '/shakespeare/:name/TARS',
    '/shutup/:name/TARS',
    '/think/:name/TARS',
    '/thinking/:name/TARS',
    '/thumbs/:name/TARS',
    '/xmas/:name/TARS',
    '/yoda/:name/TARS',
    '/you/:name/TARS'
];

var sitesToSummarize = [
    'abcnews.go.com/',
    'androidpolice.com/',
    'bbc.com/',
    'bleedingcool.com/',
    'www.bloomberg.com/',
    'businessinsider.com/',
    'cbsnews.com/',
    'cnbc.com/',
    'cnn.com/',
    'engadget.com/',
    'espn.com/',
    'fivethirtyeight.com/',
    'foxnews.com/',
    'gamespot.com/',
    'gizmodo.com/',
    'hollywoodreporter.com/',
    'huffingtonpost.com/',
    'ign.com/',
    'mashable.com/',
    'msnbc.com/',
    'newsobserver.com/',
    'newsweek.com/',
    'newyorker.com/',
    'npr.org/',
    'nytimes.com/',
    'politico.com/',
    'polygon.com/',
    'propublica.org/',
    'qz.com/',
    'slate.com/',
    'techcrunch.com/',
    'teenvogue.com/',
    'theguardian.com/',
    'thehill.com/',
    'theintercept.com/',
    'theverge.com/',
    'theweek.com/',
    'variety.com/',
    'vice.com/',
    'vox.com/',
    'washingtonpost.com/',
    'wired.co.uk/',
    'wral.com/'
];

var menus = {
    'alpaca chicken': 'http://www.alpacachicken.com/menu.html',
    'azitra': 'http://www.azitra.us/images/menu/7046843_Lunch_Menu_February_2018.pdf',
    'babymoon cafe': 'https://www.babymooncafe.com/our-menu/',
    'bad daddy\'s': 'https://baddaddysburgerbar.com/store/nc/raleigh',
    'bar louie': 'http://www.barlouie.com/menu',
    'brixx': 'http://brixxpizza.com/menu/pizza/',
    'brasa': 'http://brasasteakhouse.com/menu/',
    'burgerfi': 'https://burgerfi.com/menu/',
    'carmen’s': 'http://carmenscubancafe.com/?page_id=2882',
    'carolina ale house': 'https://www.carolinaalehouse.com/menu/',
    'champa': 'https://www.champathaisushi.com/menus',
    'chipotle': 'https://www.chipotle.com/menu',
    'chophouse': 'http://www.chophousesofnc.com/pdf/ChopHouseLunchMenu.pdf',
    'dharani': 'http://www.dharanius.com/morrisville/pdf/',
    'firehouse': 'https://www.firehousesubs.com/our-food/',
    'first watch': 'https://www.firstwatch.com/menu',
    'flame kebob': 'https://www.flamekabob.com/menu',
    'flying burrito': 'http://www.originalflyingburrito.com/flying-burrito-menu/',
    'jason’s deli': 'https://www.jasonsdeli.com/menu',
    'lynwood grill': 'https://www.lynnwoodgrill.com/menu/',
    'moe\'s': 'https://www.moes.com/menu',
    'pei wei': 'https://order.peiwei.com/menu/108-brier-creek',
    'red robin': 'https://www.redrobin.com/content/dam/web/menu/printable/menu-rrgb-t2.pdf',
    'san jose': 'http://sanjosetacosandtequilas.com/wp-content/uploads/2018/03/San_Jose_Menu_Skyland.pdf',
    'smokey’s bbq': 'http://www.smokeysshack.com/menu',
    'taco bell': 'https://www.tacobell.com/food',
    'tamarind': 'https://tamarindeatery.revelup.com/weborder/',
    'tasu': 'http://shikitasu.com/wp-content/uploads/2017/10/lunch-menu-10-19-17.pdf',
    'trali': 'http://www.traliirishpub.com/lunch-dinner-menu/',
    'which wich': 'https://www.whichwich.com/menu/',
    'your pie': 'https://yourpie.com/menu/',
    'zayka': 'https://zaykaraleigh.com/our-menu/'
}

var lunch = [
    ':cubimal_chick: alpaca chicken',
    ':flag-in: azitra',
    ':beer: beer garden',
    ':pizza: brixx',
    ':hamburger: burgerfi',
    ':flag-mx: chipotle',
    ':fire_engine: firehouse subs',
    ':pancakes: first watch',
    ':fire: flame kebob',
    ':burrito: flying burrito',
    ':sandwich: jason’s deli',
    ':cut_of_meat: lynwood',
    ':avocado: moe’s',
    ':bird: red robin',
    ':taco: san jose',
    ':bell: taco bell',
    ':curry: tamarind',
    ':sushi: tasu',
    ':baguette_bread: which wich',
    ':pie: your pie',
    ':rice: zayka'
];

var people = [
    'Andres',
    'Brett',
    'Frank',
    'Jamie',
    'Linda',
    'Lura',
    'Melanie',
    'Rachel',
    'Ryan'
];

var trucks = {
    '13th taco': 'http://the13thtaco.com',
    '454 grill': 'https://www.454grillfoodtruck.com',
    '815 gourmet grill': 'https://www.815gourmetgrill.com',
    'a taste of aloha': 'https://www.facebook.com/Atouchofaloha',
    'acai monster': 'https://www.monsterfoodtrucks.com/acai-menu.html',
    'adobo joe': 'https://www.facebook.com/Adobo-Joe-Food-Truck-1496999187293585',
    'all american': 'http://www.allamericanrdu.com',
    'american meltdown': 'http://www.americanmeltdown.org',
    'an edible perspective': 'https://anedibleperspective.com',
    'arepa culture nc': 'http://www.arepaculturenc.com',
    'baguettaboutit': 'http://www.baguettaboutit.com',
    'bam pow chow': 'http://www.bampowchow.com/our-menu.html',
    'barone meatball co': 'https://baronemeatball.com',
    'baton rouge cuisine': 'http://www.brcuisine.com',
    'bbq proper': 'http://bbqproper.com',
    'belgian waffle crafters': 'https://belgianwafflecrafters.com',
    'bo\'s kitchen': 'http://www.boskc.com',
    'boricua soul': 'https://boricuasoulnc.com',
    'bourbon street beignets': 'http://bourbonstreetbeignets.com/index.html',
    'buoy bowls': 'http://buoybowls.com/',
    'brewer\'s italian ice': 'https://brewersitalianice.com',
    'brusters ice cream': 'http://brusters.com',
    'bulkogi korean bbq': 'http://www.bulkogikrnbbq.com/menu',
    'buzzy bakes': 'https://www.buzzybakes.com',
    'caribbean kicker': 'https://www.caribbeankicker.com/',
    'caffe bellezza': 'http://caffebellezza.com',
    'cheesecake lady': 'https://tanyasteele.vpweb.com',
    'chez moi bakery': 'https://www.iloverumcake.com',
    'chick-n-que': 'http://www.chicknque.com',
    'chirba chirba': 'https://www.chirbachirba.com',
    'cockadoodlemoo': 'http://cockadoodlemootruck.com',
    'coco crissi shaved ice': 'http://www.cococrissi.com',
    'cocoa forte': 'http://www.cocoafortedesserts.com',
    'crispy gyoza': 'http://www.crispygyoza.com',
    'curry in a hurry': 'https://curryinahurrytruck.com',
    'daddy bob\'s bbq': 'https://www.daddybobsbarbeque.com',
    'del\'s frozen lemonade': 'https://dels.com',
    'fahsyrah\'s lemonade': 'https://www.fahsyrahslemonade.com',
    'fat boys kitchen':'https://www.fatboysnc.com',
    'fresh local ice cream': 'http://www.freshlocalicecream.com',
    'frostbites': 'https://www.facebook.com/FrostBitesofFranklinton',
    'gettin sauced in the city': 'https://www.gettinsaucedinthecity.com',
    'gussys': 'http://www.gussys.com',
    'hibachi xpress': 'https://www.hibachixpress.com/food-truck',
    'holy mole': 'https://www.holymolemyenchiladas.com',
    'holy moly cannoli': 'https://www.holymolycannoli.com/',
    'hot chix hotcakes': 'http://www.hotcakesandchicken.com',
    'ice cream boss': 'http://www.icecreambossnc.com',
    'jam ice cream': 'http://www.jamicecream.com',
    'king\'s authentic phillys': 'https://www.facebook.com/KingsPhillyCheesesteaks',
    'kono pizza': 'http://konousa.com',
    'la republica taco': 'https://www.facebook.com/lareublicafoodtrucks',
    'lee\'s kitchen': 'http://leeskitchenjamaican.com',
    'lo yo on the go': 'https://www.facebook.com/pages/category/Frozen-Yogurt-Shop/Loyo-On-The-Go-246950718669827/',
    'lugia\'s ice cream': 'https://lugiasicecream.com',
    'mama voula\'s': 'https://www.mamavoulas.com',
    'medley': 'https://www.medleync.com',
    'mexiarepa grill': 'http://www.mexiarepagrill.com/',
    'moonrunners': 'http://www.moonrunnerstruck.com',
    'mr a\'s beignets':'https://www.squaredoughnuts.com',
    'not just icing': 'http://www.notjusticing.com',
    'oak city fish & chips': 'http://www.oakcityfishandchips.com',
    'only burger': 'http://onlyburger.com',
    'pie pushers': 'https://www.piepushers.com',
    'poblanos tacos': 'http://www.poblanostacos.com',
    'pork in the road': 'http://porkintheroad.net',
    'qspresso cubanos': 'https://www.qspressocubanos.com',
    'queso monster': 'https://www.monsterfoodtrucks.com/queso-menu.html',
    'r&b grill': 'http://robinsonb59.wixsite.com/wwwrbgrillandconcessionscom',
    'r&j\'s fish & wings': 'https://www.facebook.com/R-Js-Fish-Wings-1166076990088383',
    'rare earth farms': 'https://www.facebook.com/RareEarthFarmsFoodTruck',
    'rolling bistro': 'http://www.rollingbistro.net',
    'route bistro': 'http://routebistro.com',
    'sarge': 'https://www.facebook.com/Sarges-Chef-on-Wheels-202728753143835',
    'southern snack shack': 'http://www.southsnackshack.com',
    'spanglish': 'http://spanglish.comidagroup.com',
    'spud kings': 'http://spudking.com',
    'stavi\'s sandwiches': 'https://stavissandwiches.com',
    'stuft': 'http://stuft.org',
    'taco grande': 'https://tacograndenc.com/',
    'tacos las gringas': 'https://www.tacoslasgringas.com',
    'the shrimp truck': 'https://www.facebook.com/Shrimptrucknc',
    'ty\'s all natural': 'http://tysallnatural.com',
    'sympathy for the deli': 'http://www.sympathyforthedeli.com',
    'tenco coffee': 'https://www.tencocoffee.com',
    'thai box zing': 'http://www.thaiboxzing.com',
    'the bamboo cookhouse': 'https://www.thebamboocookhouse.com',
    'the corner venezuelan': 'http://www.thecornervzla.com',
    'the cow and the oak': 'http://www.cowandoak.com',
    'the heights': 'https://www.theheightsdk.com',
    'the humble pig': 'http://www.thehumblepig.com/index.html',
    'the kupkake fairy': 'https://www.facebook.com/thekupkakefairy',
    'the potato wagon': 'https://www.thepotatowagonllc.com',
    'two roosters ice cream': 'http://www.tworoosters.com',
    'umami on wheels': 'https://www.facebook.com/umamionwheels/',
    'wandering moose': 'http://www.wanderingmoosenc.com',
    'will & pops': 'http://www.willandpops.com',
    'wingskis': 'http://www.wingskisnc.com'
}

var alt_trucks = {
    '454 grill food truck': 'https://www.454grillfoodtruck.com',
    'arepa culture': 'http://www.arepaculturenc.com',
    'bampowchow': 'http://www.bampowchow.com/our-menu.html',
    'gettin\' sauced': 'https://www.gettinsaucedinthecity.com',
    'hot chix': 'http://www.hotcakesandchicken.com',
    'la republicataco': 'https://www.facebook.com/lareublicafoodtrucks',
    'las gringas': 'https://www.tacoslasgringas.com',
    'moonrunnerstruck': 'http://www.moonrunnerstruck.com',
    'oakcityfishandchips': 'http://www.oakcityfishandchips.com',
    'thepotatowagon': 'https://www.thepotatowagonllc.com',
    'umamionwheels': 'https://www.facebook.com/umamionwheels/',
    'will & pop\'s': 'http://www.willandpops.com'
}

module.exports = {
    fuckOff: fuckOff,
    sitesToSummarize: sitesToSummarize,
    menus: menus,
    lunch: lunch,
    people: people,
    trucks: trucks,
    alt_trucks: alt_trucks
}