var fuckOff = [
    '/back/:name/TARS',
    '/ballmer/:name/the AKC/TARS',
    '/bday/:name/TARS',
    '/blackadder/:name/TARS',
    '/bm/:name/TARS',
    '/bus/:name/TARS',
    '/chainsaw/:name/TARS',
    '/cocksplat/:name/TARS',
    '/dalton/:name/TARS',
    '/deraadt/:name/TARS',
    '/donut/:name/TARS',
    '/equity/:name/TARS',
    '/gfy/:name/TARS',
    '/ing/:name/TARS',
    '/keep/:name/TARS',
    '/king/:name/TARS',
    '/linus/:name/TARS',
    '/look/:name/TARS',
    '/madison/:name/TARS',
    '/nugget/:name/TARS',
    '/off/:name/TARS',
    '/outside/:name/TARS',
    '/problem/:name/TARS',
    '/shakespeare/:name/TARS',
    '/shutup/:name/TARS',
    '/think/:name/TARS',
    '/thinking/:name/TARS',
    '/thumbs/:name/TARS',
    '/xmas/:name/TARS',
    '/yoda/:name/TARS',
    '/you/:name/TARS'
];

var sitesToSummarize = [
    'abcnews.go.com/',
    'androidpolice.com/',
    'bbc.com/',
    'bleedingcool.com/',
    'cbsnews.com/',
    'cnn.com/',
    'engadget.com/',
    'espn.com/',
    'fivethirtyeight.com/',
    'foxnews.com/',
    'huffingtonpost.com/',
    'ign.com/',
    'msnbc.com/',
    'npr.org/',
    'politico.com/',
    'polygon.com/',
    'slate.com/',
    'teenvogue.com/',
    'thehill.com/',
    'theintercept.com/',
    'theverge.com/',
    'vice.com/',
    'vox.com/',
    'washingtonpost.com/',
    'wral.com/'
];

var menus = {
    'alpaca chicken': 'http://www.alpacachicken.com/menu.html',
    'azitra': 'http://www.azitra.us/images/menu/7046843_Lunch_Menu_February_2018.pdf',
    'bar louie': 'http://www.barlouie.com/menu',
    'brixx': 'http://brixxpizza.com/menu/pizza/',
    'brasa': 'http://brasasteakhouse.com/menu/',
    'carolina ale house': 'https://www.carolinaalehouse.com/menu/',
    'champa': 'https://www.champathaisushi.com/menus',
    'jason’s deli': 'https://www.jasonsdeli.com/menu',
    'pei wei': 'https://order.peiwei.com/menu/108-brier-creek',
    'red robin': 'https://www.redrobin.com/content/dam/web/menu/printable/menu-rrgb-t2.pdf',
    'san jose': 'http://sanjosetacosandtequilas.com/wp-content/uploads/2018/03/San_Jose_Menu_Skyland.pdf',
    'tamarind': 'https://tamarindeatery.revelup.com/weborder/',
    'tasu': 'http://shikitasu.com/wp-content/uploads/2017/10/lunch-menu-10-19-17.pdf',
    'trali': 'http://www.traliirishpub.com/lunch-dinner-menu/',
    'which wich': 'https://www.whichwich.com/menu/',
    'your pie': 'https://yourpie.com/menu/',
    'zayka': 'https://zaykaraleigh.com/our-menu/'
}

var people = [
    'Andres',
    'Brett',
    'Frank',
    'Jamie',
    'Linda',
    'Lura',
    'Melanie',
    'Rachel',
    'Ryan'
];

var trucks = {
    '13th taco': 'http://the13thtaco.com/',
    '454 grill': 'https://www.454grillfoodtruck.com/',
    'american meltdown': 'http://www.americanmeltdown.org',
    'an edible perspective': 'https://anedibleperspective.com/',
    'baguettaboutit': 'http://www.baguettaboutit.com/',
    'belgian waffle crafters': 'https://belgianwafflecrafters.com/',
    'bo\'s kitchen': 'http://www.boskc.com/',
    'boricua soul': 'https://boricuasoulnc.com/',
    'caffe bellezza': 'http://caffebellezza.com/',
    'chick-n-que': 'http://www.chicknque.com/',
    'chirba chirba': 'https://www.chirbachirba.com/',
    'cockadoodlemoo': 'http://cockadoodlemootruck.com/',
    'coco crissi shaved ice': 'http://www.cococrissi.com/',
    'crispy gyoza': 'http://www.crispygyoza.com/',
    'daddy bob\'s bbq': 'https://www.daddybobsbarbeque.com/',
    'del\'s frozen lemonade': 'https://dels.com/',
    'fahsyrah\'s lemonade': 'https://www.fahsyrahslemonade.com/',
    'fresh local ice cream': 'http://www.freshlocalicecream.com/',
    'frostbites': 'https://www.facebook.com/FrostBitesofFranklinton/',
    'gettin sauced in the city': 'https://www.gettinsaucedinthecity.com/',
    'hot chix hotcakes': 'http://www.hotcakesandchicken.com/',
    'ice cream boss': 'http://www.icecreambossnc.com/',
    'lee\'s kitchen': 'http://leeskitchenjamaican.com/',
    'lugia\'s ice cream': 'https://lugiasicecream.com/',
    'moonrunners': 'http://www.moonrunnerstruck.com/',
    'not just icing': 'http://www.notjusticing.com',
    'only burger': 'http://onlyburger.com/',
    'pie pushers': 'https://www.piepushers.com/',
    'poblanos tacos': 'http://www.poblanostacos.com/',
    'route bistro': 'http://routebistro.com/',
    'southern snack shack': 'http://www.southsnackshack.com/',
    'sympathy for the deli': 'http://www.sympathyforthedeli.com/',
    'thai box zing': 'http://www.thaiboxzing.com/',
    'the bamboo cookhouse': 'https://www.thebamboocookhouse.com',
    'the corner venezuelan': 'http://www.thecornervzla.com/',
    'the cow and the oak': 'http://www.cowandoak.com/',
    'the humble pig': 'http://www.thehumblepig.com/index.html'
}

module.exports = {
    fuckOff: fuckOff,
    sitesToSummarize: sitesToSummarize,
    menus: menus,
    people: people,
    trucks: trucks
}