var fuckOff = [
    '/back/:name/TARS',
    '/ballmer/:name/the AKC/TARS',
    '/bday/:name/TARS',
    '/blackadder/:name/TARS',
    '/bm/:name/TARS',
    '/bus/:name/TARS',
    '/chainsaw/:name/TARS',
    '/cocksplat/:name/TARS',
    '/dalton/:name/TARS',
    '/deraadt/:name/TARS',
    '/donut/:name/TARS',
    '/equity/:name/TARS',
    '/gfy/:name/TARS',
    '/ing/:name/TARS',
    '/keep/:name/TARS',
    '/king/:name/TARS',
    '/linus/:name/TARS',
    '/look/:name/TARS',
    '/madison/:name/TARS',
    '/nugget/:name/TARS',
    '/off/:name/TARS',
    '/outside/:name/TARS',
    '/problem/:name/TARS',
    '/shakespeare/:name/TARS',
    '/shutup/:name/TARS',
    '/think/:name/TARS',
    '/thinking/:name/TARS',
    '/thumbs/:name/TARS',
    '/xmas/:name/TARS',
    '/yoda/:name/TARS',
    '/you/:name/TARS'
];

var sitesToSummarize = [
    'abcnews.go.com/',
    'androidpolice.com/',
    'bbc.com/',
    'bleedingcool.com/',
    'businessinsider.com/',
    'cbsnews.com/',
    'cnbc.com/',
    'cnn.com/',
    'engadget.com/',
    'espn.com/',
    'fivethirtyeight.com/',
    'foxnews.com/',
    'huffingtonpost.com/',
    'ign.com/',
    'mashable.com/',
    'msnbc.com/',
    'newsobserver.com/',
    'newsweek.com/',
    'npr.org/',
    'nytimes.com/',
    'politico.com/',
    'polygon.com/',
    'slate.com/',
    'techcrunch.com/',
    'teenvogue.com/',
    'thehill.com/',
    'theintercept.com/',
    'theverge.com/',
    'theweek.com/',
    'variety.com/',
    'vice.com/',
    'vox.com/',
    'washingtonpost.com/',
    'wired.co.uk/',
    'wral.com/'
];

var menus = {
    'alpaca chicken': 'http://www.alpacachicken.com/menu.html',
    'azitra': 'http://www.azitra.us/images/menu/7046843_Lunch_Menu_February_2018.pdf',
    'babymoon cafe': 'https://www.babymooncafe.com/our-menu/',
    'bar louie': 'http://www.barlouie.com/menu',
    'brixx': 'http://brixxpizza.com/menu/pizza/',
    'brasa': 'http://brasasteakhouse.com/menu/',
    'burgerfi': 'https://burgerfi.com/menu/',
    'carmen’s': 'http://carmenscubancafe.com/?page_id=2882',
    'carolina ale house': 'https://www.carolinaalehouse.com/menu/',
    'champa': 'https://www.champathaisushi.com/menus',
    'chophouse': 'http://www.chophousesofnc.com/pdf/ChopHouseLunchMenu.pdf',
    'dharani': 'http://www.dharanius.com/morrisville/pdf/',
    'firehouse subs': 'https://www.firehousesubs.com/our-food/',
    'first watch': 'https://www.firstwatch.com/menu',
    'flying burrito': 'http://www.originalflyingburrito.com/flying-burrito-menu/',
    'jason’s deli': 'https://www.jasonsdeli.com/menu',
    'pei wei': 'https://order.peiwei.com/menu/108-brier-creek',
    'red robin': 'https://www.redrobin.com/content/dam/web/menu/printable/menu-rrgb-t2.pdf',
    'san jose': 'http://sanjosetacosandtequilas.com/wp-content/uploads/2018/03/San_Jose_Menu_Skyland.pdf',
    'smokey’s bbq': 'http://www.smokeysshack.com/menu',
    'tamarind': 'https://tamarindeatery.revelup.com/weborder/',
    'tasu': 'http://shikitasu.com/wp-content/uploads/2017/10/lunch-menu-10-19-17.pdf',
    'trali': 'http://www.traliirishpub.com/lunch-dinner-menu/',
    'which wich': 'https://www.whichwich.com/menu/',
    'your pie': 'https://yourpie.com/menu/',
    'zayka': 'https://zaykaraleigh.com/our-menu/'
}

var lunch = [
    ':cubimal_chick: alpaca chicken',
    ':flag-in: azitra',
    ':pizza: brixx',
    ':beer: carolina ale house',
    ':chopsticks: champa',
    ':fire_engine: firehouse subs',
    ':burrito: flying burrito',
    ':bread: jason’s deli',
    ':bird: red robin',
    ':taco: san jose',
    ':curry: tamarind',
    ':sushi: tasu',
    ':potato: trali',
    ':baguette_bread: which wich',
    ':pie: your pie',
    ':rice: zayka'
];

var people = [
    'Andres',
    'Brett',
    'Frank',
    'Jamie',
    'Linda',
    'Lura',
    'Melanie',
    'Rachel',
    'Ryan'
];

var trucks = {
    '13th taco': 'http://the13thtaco.com/',
    '454 grill': 'https://www.454grillfoodtruck.com/',
    'a taste of aloha': 'https://www.facebook.com/Atouchofaloha/',
    'adobo joe': 'https://www.facebook.com/Adobo-Joe-Food-Truck-1496999187293585/',
    'american meltdown': 'http://www.americanmeltdown.org',
    'an edible perspective': 'https://anedibleperspective.com/',
    'arepa culture': 'http://www.arepaculturenc.com/',
    'baguettaboutit': 'http://www.baguettaboutit.com/',
    'belgian waffle crafters': 'https://belgianwafflecrafters.com/',
    'bo\'s kitchen': 'http://www.boskc.com/',
    'boricua soul': 'https://boricuasoulnc.com/',
    'brewer\'s italian ice': 'https://brewersitalianice.com/',
    'brusters ice cream': 'http://brusters.com/',
    'caffe bellezza': 'http://caffebellezza.com/',
    'chick-n-que': 'http://www.chicknque.com/',
    'chirba chirba': 'https://www.chirbachirba.com/',
    'cockadoodlemoo': 'http://cockadoodlemootruck.com/',
    'coco crissi shaved ice': 'http://www.cococrissi.com/',
    'cocoa forte': 'http://www.cocoafortedesserts.com/',
    'crispy gyoza': 'http://www.crispygyoza.com/',
    'curry in a hurry': 'https://curryinahurrytruck.com/',
    'daddy bob\'s bbq': 'https://www.daddybobsbarbeque.com/',
    'del\'s frozen lemonade': 'https://dels.com/',
    'fahsyrah\'s lemonade': 'https://www.fahsyrahslemonade.com/',
    'fresh local ice cream': 'http://www.freshlocalicecream.com/',
    'frostbites': 'https://www.facebook.com/FrostBitesofFranklinton/',
    'gettin sauced in the city': 'https://www.gettinsaucedinthecity.com/',
    'gussys': 'http://www.gussys.com/',
    'hot chix hotcakes': 'http://www.hotcakesandchicken.com/',
    'ice cream boss': 'http://www.icecreambossnc.com/',
    'kono pizza': 'http://konousa.com/',
    'lee\'s kitchen': 'http://leeskitchenjamaican.com/',
    'lugia\'s ice cream': 'https://lugiasicecream.com/',
    'moonrunners': 'http://www.moonrunnerstruck.com/',
    'not just icing': 'http://www.notjusticing.com',
    'only burger': 'http://onlyburger.com/',
    'pie pushers': 'https://www.piepushers.com/',
    'poblanos tacos': 'http://www.poblanostacos.com/',
    'pork in the road': 'http://porkintheroad.net/',
    'queso monster': 'https://www.facebook.com/Queso-Monster-1017749471605161/',
    'route bistro': 'http://routebistro.com/',
    'southern snack shack': 'http://www.southsnackshack.com/',
    'spanglish': 'http://spanglish.comidagroup.com/',
    'tacos las gringas': 'https://www.tacoslasgringas.com/',
    'sympathy for the deli': 'http://www.sympathyforthedeli.com/',
    'tenco coffee': 'https://www.tencocoffee.com/',
    'thai box zing': 'http://www.thaiboxzing.com/',
    'the bamboo cookhouse': 'https://www.thebamboocookhouse.com',
    'the corner venezuelan': 'http://www.thecornervzla.com/',
    'the cow and the oak': 'http://www.cowandoak.com/',
    'the humble pig': 'http://www.thehumblepig.com/index.html',
    'the potato wagon': 'https://www.thepotatowagonllc.com/',
    'two roosters ice cream': 'http://www.tworoosters.com/',
    'will & pops': 'http://www.willandpops.com/'
}

module.exports = {
    fuckOff: fuckOff,
    sitesToSummarize: sitesToSummarize,
    menus: menus,
    lunch: lunch,
    people: people,
    trucks: trucks
}